# action.yml
name: 'csvbeer'
description: 'Generate BeerProto canonical encoded JSON from CSV'
inputs:
  command:
    description: 'Command to run, (hops, equipments, styles)'
    required: true
    default: 'hops'
  inputFile:
    description: 'File for the command to run, (e.g. hops.csv, equipments.csv, styles.csv)'
    required: true
    default: 'hops.csv'
  output:
    description: 'Output processed from CSV to (file, tty)'
    required: false
    default: 'file'
  outputFile:
    description: 'File output name'
    required: false
    default: 'hops.json'
  index:
      description: 'Name of the index file to identify (Equipment IDs)'
      required: false
      default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.command }}'
    - '${{ inputs.inputFile }}'
    - '--output=${{ inputs.output }}'
    - '--file=${{ inputs.outputFile }}'
    - '--index=${{ inputs.index }}'