version: "3.8"
services:
  hops:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./hops/hops.csv:/data/hops.csv"
      - "./json/:/json"
    command:
      [
        "hops",
        "/data/hops.csv",
        "--output",
        "file",
        "--file",
        "/json/hops.json",
      ]
  equipments:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./equipment/equipmentItems.csv:/data/equipmentItems.csv"
      - "./equipment/equipment.csv:/data/equipment.csv"
      - "./json/:/json"
    command:
      [
          "equipments",
          "/data/equipmentItems.csv",
          "--index",
          "/data/equipment.csv",
          "--output",
          "file",
          "--file",
          "/json/equipment.json",
      ]
  styles:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./styles/styles.csv:/data/styles.csv"
      - "./json/:/json"
    command:
      [
          "styles",
          "/data/styles.csv",
          "--output",
          "file",
          "--file",
          "/json/styles.json",
      ]
  mash:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./mash/mashSteps.csv:/data/mashSteps.csv"
      - "./mash/mash.csv:/data/mash.csv"
      - "./json/:/json"
    command:
      [
          "mash",
          "/data/mashSteps.csv",
          "--index",
          "/data/mash.csv",
          "--output",
          "file",
          "--file",
          "/json/mash.json",
      ]
  fermentation:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./fermentation/fermentationSteps.csv:/data/fermentationSteps.csv"
      - "./fermentation/fermentation.csv:/data/fermentation.csv"
      - "./json/:/json"
    command:
      [
          "fermentation",
          "/data/fermentationSteps.csv",
          "--index",
          "/data/fermentation.csv",
          "--output",
          "file",
          "--file",
          "/json/fermentation.json",
      ]
  water:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./water/profiles.csv:/data/profiles.csv"
      - "./json/:/json"
    command:
      [
          "water",
          "/data/profiles.csv",
          "--output",
          "file",
          "--file",
          "/json/water.json",
      ]
  packaging:
    build:
      context: ".github/actions/csvbeer"
    volumes:
      - "./packaging/packaging.csv:/data/packaging.csv"
      - "./json/:/json"
    command:
      [
          "packaging",
          "/data/packaging.csv",
          "--output",
          "file",
          "--file",
          "/json/packaging.json",
      ]