version: "3.8"
services:
  csvbeer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../hops/hops.csv:/data/hops.csv"
      - "../json/:/json"
    command:
      [
        "hops",
        "/data/hops.csv",
        "--output",
        "file",
        "--file",
        "/json/hops.json",
      ]
