name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: csvbeer
        uses: ./.github/actions/csvbeer
        with:
          inputFile: '${{ GITHUB_WORKSPACE }}/hops/hops.csv'
