name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  JSON:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: csvbeer
        uses: ./.github/actions/csvbeer
        with:
          commandf: 'hops'
          inputFile: '/github/workspace/hops/hops.csv'
