name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  JSON:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: csvbeer
        uses: ./.github/actions/csvbeer
        with:
          command: 'hops'
          inputFile: '/github/workspace/hops/hops.csv'
          outputFile: '/github/workspace/json/hops.json'
      - name: Git Commit on Workflow
          uses: matheusalbino/git-commit@v1.0.1
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            message: Updating JSON files
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false