name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  JSON:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hops
        uses: ./.github/actions/csvbeer
        with:
          command: 'hops'
          inputFile: '/github/workspace/hops/hops.csv'
          outputFile: '/github/workspace/json/hops.json'

      - name: equipments
        uses: ./.github/actions/csvbeer
        with:
          command: 'equipments'
          inputFile: '/github/workspace/equipment/equipmentItems.csv'
          index: '/github/workspace/equipment/equipment.csv'
          outputFile: '/github/workspace/json/equipment.json'

      - name: styles
        uses: ./.github/actions/csvbeer
        with:
          command: 'styles'
          inputFile: '/github/workspace/styles/styles.csv'
          outputFile: '/github/workspace/json/styles.json'

      - name: mash
        uses: ./.github/actions/csvbeer
        with:
          command: 'mash'
          inputFile: '/github/workspace/mash/mashSteps.csv'
          index: '/github/workspace/mash/mash.csv'
          outputFile: '/github/workspace/json/mash.json'

      - name: fermentation
        uses: ./.github/actions/csvbeer
        with:
          command: 'fermentation'
          inputFile: '/github/workspace/fermentation/fermentationSteps.csv'
          index: '/github/workspace/mash/fermentation.csv'
          outputFile: '/github/workspace/json/fermentation.json'

      - name: Git Commit on Workflow
        uses: matheusalbino/git-commit@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: Updating JSON files